global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['${EC2_HOST}:9100']

remote_write:
- url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
  basic_auth:
    username: 1898242
    password: ${GRAFANA_API_KEY}
